IS2GRUPO9/Models/Proyecto.cs
using IS2GRUPO9.Repositorios;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace IS2GRUPO9.Models
{
    [Table("PROYECTOS")]
    public class Proyecto
    {
        private readonly ILineaBaseRepositorio lineaBaseRepositorio;
        private readonly IProyectoRepositorio proyectoRepositorio;

        private readonly IUsuarioRepositorio usuarioRepositorio;
        public Proyecto()
        {
            this.lineaBaseRepositorio = new LineaBaseRepositorio();
            this.usuarioRepositorio = new UsuarioRepositorio();
            this.proyectoRepositorio = new ProyectoRepositorio();
        }
        
        [Column("ID")]
        public int Id { get; set; }

        [Column("NOMBRE")]
        public String Nombre { get; set; }

        [Column("DESCRIPCION")]
        public String Descripcion { get; set; }

        [Column("FECHA_CREACION")]
        public DateTime FechaCreacion { get; set; }

        [Column("ID_ENCARGADO")]
        public int IdEncargado { get; set; }

        [Column("ID_LINEA_BASE")]
        public int IdLineaBase { get; set; }

        [NotMapped]
        public LineaBase LineaBaseProyecto { get { return this.lineaBaseRepositorio.ObtenerLineaBase(this.IdLineaBase); } }

        [NotMapped]
        public Usuario UsuarioEncargado
        {
            get { return this.usuarioRepositorio.ObtenerUsuario(this.IdEncargado); }
        }

        [NotMapped]
        public List<RequerimientoProyecto> Requerimientos { get { return this.proyectoRepositorio.ObtenerRequerimientos(this.Id); } }

        public void AgregarRequerimiento(String descripcion, String prioridad)
        {
            var requerimiento = new RequerimientoProyecto();
            requerimiento.IdProyecto = this.Id;
            requerimiento.Descripcion = descripcion;
            requerimiento.Prioridad = prioridad;
            this.proyectoRepositorio.AgregarRequerimiento(requerimiento);
        }
    }
}

IS2GRUPO9/Controllers/ProyectosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IS2GRUPO9.Models;
using IS2GRUPO9.Repositorios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace IS2GRUPO9.Controllers
{
    public class ProyectosController : Controller
    {
        private readonly IUsuarioRepositorio usuariosRepositorio;
        private readonly IProyectoRepositorio proyectoRepositorio;
        private readonly ILineaBaseRepositorio lineaBaseRepositorio;

        public ProyectosController()
        {
            usuariosRepositorio = new UsuarioRepositorio();
            proyectoRepositorio = new ProyectoRepositorio();
            lineaBaseRepositorio = new LineaBaseRepositorio();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = this.proyectoRepositorio.ObtenerTodos();
            return View(model);
        }

        public IActionResult Details(int id)
        {
            Proyecto proyecto = this.proyectoRepositorio.Obtener(id);
            return View(proyecto);
        }

        public IActionResult Create()
        {
            ViewBag.users = this.GetUsuarios();
            ViewBag.lineasBase = this.GetLineasBase();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Proyecto proyecto)
        {
            var creacionOk = this.proyectoRepositorio.Crear(proyecto);
            return this.RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            Proyecto proyecto = this.proyectoRepositorio.Obtener(id);
            ViewBag.users = this.GetUsuarios();
            ViewBag.lineasBase = this.GetLineasBase();
            return this.View(proyecto);
        }

        [HttpPost]
        public IActionResult Edit(Proyecto proyecto)
        {
            this.proyectoRepositorio.Actualizar(proyecto);
            return this.RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            Proyecto proyecto = this.proyectoRepositorio.Obtener(id);
            return this.View(proyecto);
        }

        [HttpPost]
        public IActionResult Delete(Proyecto proyecto)
        {
            if(!String.IsNullOrEmpty(Request.Form["eliminar"]))
            {
                bool borrarOk = this.proyectoRepositorio.Delete(proyecto.Id);
                if (!borrarOk)
                {
                    ViewBag.errorMessage("Ocurrió un error al eliminar el proyecto.");
                    return this.View(proyecto);
                }
            }

            return this.RedirectToAction("Index");
        }

        private List<SelectListItem> GetUsuarios()
        {
            List<Usuario> usuarios = this.usuariosRepositorio.ObtenerTodos();
            List<SelectListItem> usuariosAsignables = new List<SelectListItem>();
            foreach (var usuario in usuarios)
            {
                usuariosAsignables.Add(new SelectListItem()
                {
                    Text = usuario.NombreUsuario,
                    Value = usuario.Id.ToString()
                });
            }
            return usuariosAsignables;
        }

        private List<SelectListItem> GetLineasBase()
        {
            List<LineaBase> lineasBase = this.lineaBaseRepositorio.ObtenerLineasBaseActivas();
            List<SelectListItem> lineasBaseActivas = new List<SelectListItem>();
            foreach (var lineaBase in lineasBase)
            {
                lineasBaseActivas.Add(new SelectListItem()
                {
                    Text = lineaBase.Nombre,
                    Value = lineaBase.Codigo.ToString()
                });
            }
            return lineasBaseActivas;
        }
    }
}

IS2GRUPO9/Views/Proyectos/Crear.cshtml
@model IS2GRUPO9.Models.Proyecto
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>

<div>
    @using (Html.BeginForm("Crear", "Proyectos", FormMethod.Post, new { @class = "form-is" }))
    {
        <label>Nombre Proyecto:</label>
        @Html.TextBoxFor(model => model.Nombre)

        <br />
        <label>Descripción:</label>
        @Html.TextBoxFor(model => model.Descripcion)

        <br />
        <label>Usuario:</label>
        @Html.DropDownListFor(model => model.IdEncargado, (List<SelectListItem>)ViewBag.users)

        <br />
        <label>Línea base:</label>
        @Html.DropDownListFor(model => model.IdLineaBase, (List<SelectListItem>)ViewBag.lineasBase)

        <input type="submit" value="crear" />
    }
</div>

IS2GRUPO9/Views/Proyectos/Create.cshtml
@model IS2GRUPO9.Models.Proyecto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEncargado" class="control-label"></label>
                @Html.DropDownListFor(model => model.IdEncargado, (List<SelectListItem>)ViewBag.users, new { @class="form-control" })
                <span asp-validation-for="IdEncargado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdLineaBase" class="control-label"></label>
                @Html.DropDownListFor(model => model.IdLineaBase, (List<SelectListItem>)ViewBag.lineasBase, new { @class="form-control" })
                <span asp-validation-for="IdLineaBase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Proyectos/Delete.cshtml
@model IS2GRUPO9.Models.Proyecto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdEncargado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdEncargado)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdLineaBase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdLineaBase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IS2GRUPO9/Views/Proyectos/Details.cshtml
@model IS2GRUPO9.Models.Proyecto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdEncargado)
        </dt>
        <dd>
            @if(Model.UsuarioEncargado != null)
            {
                @Html.DisplayFor(model => model.UsuarioEncargado.NombreUsuario)
            } else
            {
                @:ningún usuario asignado.
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdLineaBase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdLineaBase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Proyectos/Edit.cshtml
@model IS2GRUPO9.Models.Proyecto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCreacion" class="control-label"></label>
                <input asp-for="FechaCreacion" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEncargado" class="control-label"></label>
                @Html.DropDownListFor(model => model.IdEncargado, (List<SelectListItem>)ViewBag.users, new { @class = "form-control" })
                <span asp-validation-for="IdEncargado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdLineaBase" class="control-label"></label>
                @Html.DropDownListFor(model => model.IdLineaBase, (List<SelectListItem>)ViewBag.lineasBase, new { @class = "form-control" })
                <span asp-validation-for="IdLineaBase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Proyectos/Eliminar.cshtml
@model IS2GRUPO9.Models.Proyecto
@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar</h2>

@using (Html.BeginForm("Eliminar", "Proyectos", FormMethod.Post, new { id = "eliminarProyectoForm" }))
{
    if (!String.IsNullOrEmpty(ViewBag.errorMessage))
    {
        <div>
            <h5>@ViewBag.errorMessage</h5>
        </div>
    }

<div>
    <div>
        <h1>@Model.Nombre</h1>
    </div>

    <div>
        <table>
            <tbody>
                <tr>
                    <td><label>Código de proyecto:</label></td>
                    <td><label>@Model.Id</label></td>
                </tr>
                <tr>
                    <td><label>Descripción del proyecto:</label></td>
                    <td><label>@Model.Descripcion</label></td>
                </tr>
                <tr>
                    <td><label>Fecha de inicio:</label></td>
                    <td><label>@Model.FechaCreacion</label></td>
                </tr>

                <tr>
                    <td><label>Descripción de proyecto:</label></td>
                    <td><label>@Model.Descripcion</label></td>
                </tr>
                <tr>
                    <td><label>Encargado:</label></td>
                    @if (Model.UsuarioEncargado != null)
                    {
                        <td><label>@Model.LineaBaseProyecto.Nombre</label></td>
                    }
                    else
                    {
                        <td><label>Sin usuario encargado.</label></td>
                    }
                </tr>
                <tr>
                    <td><label>Línea base:</label></td>
                    @if (Model.LineaBaseProyecto != null)
                    {
                        <td><label>@Model.LineaBaseProyecto.Nombre</label></td>
                    }
                    else
                    {
                        <td><label>Línea base no asignada.</label></td>
                    }
                </tr>
            </tbody>
        </table>
    </div>
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.IdEncargado)
    @Html.HiddenFor(model => model.IdLineaBase)
    @Html.HiddenFor(model => model.Descripcion)
    @Html.HiddenFor(model => model.FechaCreacion)
    @Html.HiddenFor(model => model.Nombre)
    <div>
        <input type="submit" name="eliminar" value="eliminar" />
        <input type="submit" name="cancelar" value="cancelar" />
    </div>
</div>
}

IS2GRUPO9/Views/Proyectos/Index.cshtml
@model List<Proyecto>
@{
    ViewData["Title"] = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table-is {
        background-color: #f3f3f3;
    }
    .table-is {
        width: 100%;
    }
    .table-is td:first-child, .table-is th:first-child {
        text-align: center;
    }
    .table-is td {
        padding: 6px;
    }
</style>

<h2>Lista</h2>

<div>
    <table class="table-is">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Línea base</th>
                <th>Encargado</th>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var proyecto in Model)
            {
            <tr>
                <td>@Html.ActionLink("1", "Details", "Proyectos", new { id = 1 })</td>
                <td>@proyecto.Nombre</td>
                <td>@proyecto.Descripcion</td>
                @if (proyecto.LineaBaseProyecto != null)
                {
                    <td>@proyecto.LineaBaseProyecto.Nombre</td>
                }
                else
                {
                    <td>ninguna línea base asignada.</td>
                }
                @if (proyecto.UsuarioEncargado != null)
                {
                    <td>@proyecto.UsuarioEncargado.NombreUsuario</td>
                }
                else
                {
                    <td>ninguna usuario asignado.</td>
                }
                <td>
                    @Html.ActionLink("Editar", "Edit", "Proyectos", new { id = proyecto.Id }) &nbsp;|&nbsp;
                    @Html.ActionLink("Eliminar", "Delete", "Proyectos", new { id = proyecto.Id })
                </td>
            </tr>
            }
        </tbody>
        
        @Html.ActionLink("Crear nuevo proyecto", "Create", "Proyectos")
    </table>
</div>

IS2GRUPO9/Views/Proyectos/Modificar.cshtml
@model IS2GRUPO9.Models.Proyecto
@{
    ViewData["Title"] = "Modificar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modificar</h2>

@using (Html.BeginForm("Modificar", "Proyecto", FormMethod.Post, new { @id = "editProjectForm" }))
{
    <label>Nombre Proyecto:</label>
    @Html.TextBoxFor(model => model.Nombre)

    <br />
    <label>Descripción:</label>
    @Html.TextBoxFor(model => model.Nombre)

    <br />
    <label>Usuario:</label>
    @Html.DropDownListFor(model => model.IdEncargado, (List<SelectListItem>)ViewBag.users)

    <br />
    <label>Línea base:</label>
    @Html.DropDownListFor(model => model.IdLineaBase, (List<SelectListItem>)ViewBag.lineasBase)

    @Html.HiddenFor(model => model.Id)
    <input type="submit" value="guardar" />
}

IS2GRUPO9/Views/Proyectos/Ver.cshtml
@model IS2GRUPO9.Models.Proyecto

@{
    ViewData["Title"] = "Ver";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdEncargado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdEncargado)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdLineaBase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdLineaBase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>