IS2GRUPO9/Models/Usuario.cs
using IS2GRUPO9.Repositorios;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace IS2GRUPO9.Models
{
    [Table("USUARIOS")]
    public class Usuario
    {
        private readonly IRolRepositorio rolRepositorio;

        public Usuario()
        {
            this.rolRepositorio = new RolRepositorio();
        }

        [Column("ID")]
        public int Id { get; set; }

        [Column("NOMBRE_USUARIO")]
        public string NombreUsuario { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("APELLIDO")]
        public string Apellido { get; set; }

        [Column("EMAIL")]
        public String Email { get; set; }

        [Column("PASS")]
        public string Password { get; set; }

        [Column("ID_ROL")]
        public int IdRol { get; set; }

        [Column("ROL")]
        public string Rol { get; set; }

        [NotMapped]
        public Rol RolUsuario { get { return this.rolRepositorio.Obtener(this.IdRol); } }
    }
}

IS2GRUPO9/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IS2GRUPO9.Models;
using IS2GRUPO9.Repositorios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace IS2GRUPO9.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRepositorio usuariosRepositorio;
        private readonly IRolRepositorio rolRepositorio;

        public UsuariosController()
        {
            usuariosRepositorio = new UsuarioRepositorio();
            rolRepositorio = new RolRepositorio();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Usuario> usuarios = usuariosRepositorio.ObtenerTodos();
            //ViewBag.usuarios = usuarios;
            return View(usuarios);
        }

        public IActionResult Crear()
        {
            ViewBag.roles = this.RolesList();
            return View();
        }

        [HttpPost]
        public IActionResult Crear(Usuario usuario)
        {
            if (this.usuariosRepositorio.AgregarUsuario(usuario))
            {
                return this.RedirectToAction("Index");
            } else
            {
                ViewBag.errorMessage = "Ocurrió un error al crear el usuario.";
                return this.View(usuario);
            }
        }

        public IActionResult Editar(int idUsuario)
        {
            Usuario usuario = this.usuariosRepositorio.ObtenerUsuario(idUsuario);
            ViewBag.roles = this.RolesList(usuario.IdRol);
            return View(usuario);
        }

        [HttpPost]
        public IActionResult Editar(Usuario usuario)
        {
            if (!this.usuariosRepositorio.ActualizarUsuario(usuario))
            {
                ViewBag.errorMessage = "Ocurrió un error al actualizar el usuario.";
                ViewBag.roles = this.RolesList(usuario.IdRol);
                return this.View(usuario);
            }
            return this.RedirectToAction("Index");
        }

        public IActionResult Eliminar(int idUsuario)
        {
            Usuario usuario = this.usuariosRepositorio.ObtenerUsuario(idUsuario);
            return this.View(usuario);
        }

        [HttpPost]
        public IActionResult Eliminar(Usuario usuario)
        {
            if (!this.usuariosRepositorio.EliminarUsuario(usuario.Id))
            {
                ViewBag.errorMessage = "Ocurrió un error al actualizar el usuario.";
                ViewBag.roles = this.RolesList(usuario.IdRol);
                return this.View(usuario);
            }
            return this.RedirectToAction("Index");
        }

        private List<SelectListItem> RolesList(int? selectedValue = null)
        {
            List<Rol> roles = this.rolRepositorio.ObtenerTodos();
            List<SelectListItem> opcionesRol = new List<SelectListItem>();
            foreach(var rol in roles)
            {
                var optionItem = new SelectListItem(rol.Nombre, rol.Id.ToString());
                if (selectedValue != null && rol.Id == selectedValue)
                {
                    optionItem.Selected = true;
                }
                opcionesRol.Add(optionItem);
            }
            return opcionesRol;
        }
    }
}

IS2GRUPO9/Views/Usuarios/Crear.cshtml
@model IS2GRUPO9.Models.Usuario

@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>

<h4>Usuario</h4>
@if(!String.IsNullOrEmpty(ViewBag.errorMessage))
{
    <label>@ViewBag.errorMessage</label>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdRol" class="control-label"></label>
                @Html.DropDownListFor(model => model.IdRol, (List<SelectListItem>)ViewBag.roles, new { @class="form-control" })<!--<input asp-for="IdRol" class="form-control" />-->
                <span asp-validation-for="IdRol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Usuarios/Editar.cshtml
@model IS2GRUPO9.Models.Usuario

@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdRol" class="control-label"></label>
                @Html.DropDownListFor(model => model.IdRol, (List<SelectListItem>)ViewBag.roles, new { @class = "form-control" })
                <span asp-validation-for="IdRol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Usuarios/Eliminar.cshtml
@model IS2GRUPO9.Models.Usuario

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdRol)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdRol)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">Cancelar</a>
    </form>
</div>

IS2GRUPO9/Views/Usuarios/Index.cshtml
@model List<Usuario>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <style>
        .table-is {
            background-color: #f3f3f3;
        }

        .table-is {
            width: 100%;
        }

            .table-is td:first-child, .table-is th:first-child {
                text-align: center;
            }

            .table-is td {
                padding: 6px;
            }
    </style>

<h2>Usuarios</h2>

<div>
    @Html.ActionLink("Crear nuevo usuario", "Crear", "Usuarios")
    <table class="table-is">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Correo electrónico</th>
                <th>Identificador</th>
                <th>Rol</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var usuario in Model)
            {
                <tr>
                    <td>@usuario.NombreUsuario</td>
                    <td>@usuario.Nombre&nbsp;@usuario.Apellido</td>
                    <td>@usuario.Email</td>
                    <td>@usuario.NombreUsuario</td>

                    @if (usuario.RolUsuario != null)
                    {
                        <td>
                            @usuario.RolUsuario.Nombre
                        </td>
                    }
                    else
                    {
                        <td>
                            ningún rol asignado.
                        </td>
                    }
                    <td>
                        @Html.ActionLink("Editar", "Editar", "Usuarios", new { idUsuario = usuario.Id })
                        <br />
                        @Html.ActionLink("Eliminar", "Eliminar", "Usuarios", new { idUsuario = usuario.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>