IS2GRUPO9/Controllers/DesarrolloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IS2GRUPO9.Models;
using IS2GRUPO9.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace IS2GRUPO9.Controllers
{
    public class DesarrolloController : Controller
    {
        private readonly IProyectoRepositorio proyectosRepositorio;
        private readonly IRequerimientoRepostorio requerimientoRepositorio;

        public DesarrolloController()
        {
            this.proyectosRepositorio = new ProyectoRepositorio();
            this.requerimientoRepositorio = new RequerimientoRepositorio();
        }

        public IActionResult Index(int idUsuario)
        {
            List<Proyecto> proyectosUsuario = this.proyectosRepositorio.ObtenerProyectosUsuario(idUsuario);
            return View(proyectosUsuario);
        }

        public IActionResult Ver(int id)
        {
            Proyecto proyecto = this.proyectosRepositorio.Obtener(id);
            return this.View(proyecto);
        }

        public IActionResult AgregarRequerimiento(int id)
        {
            RequerimientoProyecto model = new RequerimientoProyecto();
            model.IdProyecto = id;
            return View(model);
        }

        [HttpPost]
        public IActionResult AgregarRequerimiento(RequerimientoProyecto requerimiento)
        {
            this.requerimientoRepositorio.Crear(requerimiento);
            return this.RedirectToAction("Ver", new { id = requerimiento.IdProyecto });
        }

        public IActionResult EditarRequerimiento(int id)
        {
            RequerimientoProyecto model = requerimientoRepositorio.Obtener(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult EditarRequerimiento(RequerimientoProyecto requerimiento)
        {
            this.requerimientoRepositorio.Actualizar(requerimiento);
            return this.RedirectToAction("Ver", new { id = requerimiento.IdProyecto });
        }

        public IActionResult EliminarRequerimiento(int id)
        {
            RequerimientoProyecto model = requerimientoRepositorio.Obtener(id);
            return this.View(model);
        }

        [HttpPost]
        public IActionResult EliminarRequerimiento(RequerimientoProyecto requerimiento)
        {
            this.requerimientoRepositorio.Eliminar(requerimiento);
            return this.RedirectToAction("Ver", new { id = requerimiento.IdProyecto });
        }
    }
}

IS2GRUPO9/Views/Desarrollo/AgregarRequerimiento.cshtml
@model IS2GRUPO9.Models.RequerimientoProyecto

@{
    ViewData["Title"] = "AgregarRequerimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AgregarRequerimiento</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AgregarRequerimiento">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prioridad" class="control-label"></label>
                <input asp-for="Prioridad" class="form-control" />
                <span asp-validation-for="Prioridad" class="text-danger"></span>
            </div>
            @Html.HiddenFor(model => model.IdProyecto)
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Desarrollo/EditarRequerimiento.cshtml
@model IS2GRUPO9.Models.RequerimientoProyecto

@{
    ViewData["Title"] = "EditarRequerimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Requerimiento</h2>

<h4>Requerimiento Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarRequerimiento">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prioridad" class="control-label"></label>
                <input asp-for="Prioridad" class="form-control" />
                <span asp-validation-for="Prioridad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdProyecto" class="control-label"></label>
                <input asp-for="IdProyecto" class="form-control" />
                <span asp-validation-for="IdProyecto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IS2GRUPO9/Views/Desarrollo/EliminarRequerimiento.cshtml
@model IS2GRUPO9.Models.RequerimientoProyecto

@{
    ViewData["Title"] = "EliminarRequerimiento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EliminarRequerimiento</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RequerimientoProyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Prioridad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Prioridad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdProyecto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdProyecto)
        </dd>
    </dl>
    
    <form asp-action="EliminarRequerimiento">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="IdProyecto" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IS2GRUPO9/Views/Desarrollo/Index.cshtml
@model List<Proyecto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mis proyectos</h2>

<div>
    <ul>
        @foreach (var item in Model)
        {
            <li>@Html.ActionLink(item.Nombre, "Ver", "Desarrollo", new { @id=item.Id })</li>
        }
    </ul>
</div>

IS2GRUPO9/Views/Desarrollo/Ver.cshtml
@model Proyecto
@{
    ViewData["Title"] = "Ver";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var requerimientos = Model.Requerimientos;
}

    <style>
        .table-is {
            background-color: #f3f3f3;
        }

        .table-is {
            width: 100%;
        }

            .table-is td:first-child, .table-is th:first-child {
                text-align: center;
            }

            .table-is td {
                padding: 6px;
            }
    </style>

<h2>Ver</h2>

<h5>Gestión de Requerimientos</h5>
@if (requerimientos.Count > 0)
{
    <table class="table-is">
        <thead>
            <tr>
                <th>
                    Requerimiento
                </th>
                <th>
                    Prioridad
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var requerimiento in Model.Requerimientos)
            {
            <tr>
                <td>@requerimiento.Descripcion</td>
                <td>@requerimiento.Prioridad</td>
                <td>
                    @Html.ActionLink("Editar", "EditarRequerimiento", "Desarrollo", new { id = requerimiento.Id })
                    &nbsp;|&nbsp;
                    @Html.ActionLink("Eliminar", "EliminarRequerimiento", "Desarrollo", new { id = requerimiento.Id })
                </td>
            </tr>
            }
        </tbody>
    </table>
}
else
{
    <label>No se registran requerimientos.</label>
}

@Html.ActionLink("Agregar Requerimientos", "AgregarRequerimiento", "Desarrollo", new { id=Model.Id })

<h5>Tareas</h5>
<label>No se registran requerimientos.</label>